### ISSUE TITLE
README.md linking 404 issue

### ISSUE THREAD

**Issue by siwony** [jyeonjyan/TIL#1]
![스크린샷 2021-02-13 05 03 59](https://user-images.githubusercontent.com/62932968/107817086-f95d8d80-6db8-11eb-9910-4782ef7d02f0.png)
위 스크린 샷에서 Spring Boot 하위에 있는 SpringBoot를 사용한 CRUD linking이 잘못되어있습니다. :)

**Comment by jyeonjyan** [comment]
해당 repo를 private 처리해서 발생된 현상이며 
해당 repo 수정 변경 후 public 처리 하겠습니다.
