### ISSUE TITLE
/DevFeed/LearningCurve.md에 img linked error

### ISSUE THREAD

**Issue by siwony** [jyeonjyan/TIL#3]
linked error가 발생한 거 같아요
<img width="459" alt="스크린샷 2021-09-26 01 28 28" src="https://user-images.githubusercontent.com/62932968/134778861-7e4682c7-bbd8-4a06-b32b-5c45ce68f790.png">

**Comment by jyeonjyan** [comment]
귀찮아요 생각나면 fix 할게여
